### ISSUE TITLE
No opens left panel

### ISSUE THREAD

**Issue by Ved-un** [elyse0/today_subscriptions_addon#1]
No opens left panel on the Youtube
(Firefox 88)
 https://i.imgur.com/sKJtBTH.png

**Comment by elyse0** [comment]
I personally prefer to remove the left panel but... it's true that it would be better if it was optional

I'll try to add a basic configuration menu n-n!

**Comment by elyse0** [comment]
Commit https://github.com/elyse0/today_subscriptions_addon/commit/3394b4c8927bfc93d62301932f7738affaaa9346

From now on, the left bar is shown by default and it can be enabled or disabled in the preferences of the add-on n-n

![image](https://user-images.githubusercontent.com/26639800/116439352-0fee7f00-a815-11eb-9e2f-f2b95158eadc.png)

Thanks for opening this issue @Ved-un , if you have more suggestions let me know :'D!

**Comment by Ved-un** [comment]
Many thanks !
